---
abstract: 'simple database tests'
author:
  - 'Written by Mark Fowler B<mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Builder::Tester: 0.09
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DatabaseRow
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBI: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/2shortplanks/Test-DatabaseRow/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/2shortplanks/Test-DatabaseRow.git
version: 2.00
